package domain_error

const (
	// 8xxxxxx - 交易订单异常
	CANNOT_GET_TRADE_ORDER_BY_APP_ORD_ID_ERR_CODE       = `800000`
	CANNOT_UPDATE_TRADE_ORDER_CANCEL_COUNT_ERR_CODE     = `800001`
	CANNOT_UPDATE_ORDER_DRAFT_FOR_STATUS_RESON_ERR_CODE = `800002`
	CANNOT_INSERT_ORDER_DRAFT_ERR_CODE                  = `800003`
	CANNOT_UPDATE_ORDER_DRAFT_ERR_CODE                  = `800004`
	ORDER_ISNOT_OF_DRAFT_ERR_CODE                       = `800005`
	DUPLICATE_ORDER_ERR_CODE                            = `800006`
	APPORDID_EMPTY_ERR_CODE                             = `800007`
	CANNOT_DELETE_ORDER_DRAFT_FOR_STATUS_RESON_ERR_CODE = `800008`
	CANNOT_DELETE_ORDER_DRAFT_ERR_CODE                  = `800009`
	ORDER_ISNOT_OF_PENDING_REVIEW_ERR_CODE              = `800010`
	ORDER_REJECT_ERR_CODE                               = `800011`
	ORDER_REVIEW_WARING_CODE                            = `800012`
	// 81xxxxx - 交易订单后台校验异常
	NOT_IN_TRADING_TIME_ERR_CODE                  = `810000`
	COUNTERPARTY_CANNNOT_BE_EMPTY_ERR_CODE        = `810001`
	COUNTERPARTY_NOT_FOUND_ERR_CODE               = `810002`
	MISS_FIELD_ERR_CODE                           = `810003`
	COUNTERPARTY_AUTH_NOT_CONFIG_ERR_CODE         = `810004`
	COUNTERPARTY_AUTH_NOT_ENOUGH_ERR_CODE         = `810005`
	BUSINESS_PLANCODE_CANNNOT_BE_EMPTY_ERR_CODE   = `810006`
	BUSINEDD_PLAN_NOT_FOUND_ERR_CODE              = `810007`
	SYMBOL_CANNNOT_BE_EMPTY_ERR_CODE              = `810008`
	SYMBOL_NOT_FOUND_ERR_CODE                     = `810009`
	OPEN_CLOSE_CANNNOT_BE_EMPTY_ERR_CODE          = `810010`
	SYMBOL_NOT_IN_WHITE_POOL_ERR_CODE             = `810011`
	NUM_VALUE_CANNNOT_BE_EMPTY_ERR_CODE           = `810012`
	CAP_ACCT_NOT_FOUND_ERR_CODE                   = `810013`
	QTY_NOT_ENOUGH_ERR_CODE                       = `810014`
	PAR_VALUE_NOT_FOUD_ERR_CODE                   = `810015`
	SECURITY_ID_NOT_FOUD_ERR_CODE                 = `810016`
	CANNOT_FREEZE_CAPITAL_ON_TRADE_START_ERR_CODE = `810017`
	CAPITAL_AMOUNT_NOT_ENOUGH_ERR_CODE            = `810018`
	CAPITAL_AMOUNT_NEED_REVIEW_ERR_CODE           = `810019`
	CLORDID_CANNOT_BE_EMPTY_ERR_CODE              = `810020`
	SETTLE_SPEED_NOT_CORRECT_ERR_CODE             = `810021`
	ILLEGAL_FIT_TAG_ERR_CODE                      = `810022`
	RATE_LIMIT_EXCEEDED_ERR_CODE                  = `810023`
	PRODUCT_ACCT_NOT_FOUND_ERR_CODE               = `810024`
	QUOTA_LIMIT_EXCEEDED_ERR_CODE                 = `810025`
	ONLY_SUPPORT_BUY_ORDER_ERR_CODE               = `810026`
	ONLY_SUPPORT_PRICE_LIMIT_ORDER_ERR_CODE       = `810027`
	QUOTA_LIMIT_EXCEEDED_NEED_REVIEW_ERR_CODE     = `810028`
	APP_ORD_ID_TOO_LONG_ERR_CODE                  = `810029`
	GENERIC_VALUE_NOT_CORRECT_ERR_CODE            = `810030`
	COMMISSION_NOT_FOUND_ERR_CODE                 = `810031`
	INTEREST_NOT_FOUND_ERR_CODE                   = `810032`
	NOT_IN_T0_TRADING_TIME_ERR_CODE               = `810033`
	SHORT_SELL_AUTH_NOT_CONFIG_ERR_CODE           = `810034`
	SHORT_SELL_SIMBOL_ERR_CODE                    = `810035`
	CUST_QUAL_NOT_CORRECT_ERR_CODE                = `810036`
)
