package domain_error

func init() {
	registerErrMsg(map[string]string{
		CANNOT_GET_TRADE_ORDER_BY_APP_ORD_ID_ERR_CODE:       `无法找到交易订单，AppOrdID=%s`,
		CANNOT_UPDATE_TRADE_ORDER_CANCEL_COUNT_ERR_CODE:     `无法更新交易订单的取消次数，AppOrdID=%s，OrdCancelCount=%d`,
		CANNOT_UPDATE_ORDER_DRAFT_FOR_STATUS_RESON_ERR_CODE: `当前交易订单不是草稿状态或待审核状态，不能保存`,
		CANNOT_INSERT_ORDER_DRAFT_ERR_CODE:                  `无法预存交易订单`,
		CANNOT_UPDATE_ORDER_DRAFT_ERR_CODE:                  `无法更新预存交易订单`,
		ORDER_ISNOT_OF_DRAFT_ERR_CODE:                       `订单（%s）不处于草稿状态`,
		DUPLICATE_ORDER_ERR_CODE:                            `订单重复，id=%s`,
		APPORDID_EMPTY_ERR_CODE:                             `由应用层指定的订单ID (AppOrdID) 不能为空`,
		CANNOT_DELETE_ORDER_DRAFT_FOR_STATUS_RESON_ERR_CODE: `当前交易订单不是草稿状态，不能删除`,
		CANNOT_DELETE_ORDER_DRAFT_ERR_CODE:                  `无法删除预存的交易订单`,
		ORDER_ISNOT_OF_PENDING_REVIEW_ERR_CODE:              `订单（%s）不处于待审核状态，无法执行%s操作，请刷新页面查看订单最新状态`,
		ORDER_REJECT_ERR_CODE:                               `订单（%s）已被拒绝：%s`,
		ORDER_REVIEW_WARING_CODE:                            `有一笔订单（%s）待审核`,

		NOT_IN_TRADING_TIME_ERR_CODE:                  `不在可交易时间`,
		COUNTERPARTY_CANNNOT_BE_EMPTY_ERR_CODE:        `交易对手不能为空`,
		COUNTERPARTY_NOT_FOUND_ERR_CODE:               `查找不到交易对手:%v`,
		MISS_FIELD_ERR_CODE:                           `%s缺失字段:%s`,
		COUNTERPARTY_AUTH_NOT_CONFIG_ERR_CODE:         `交易对手%v的业务权限未配置`,
		COUNTERPARTY_AUTH_NOT_ENOUGH_ERR_CODE:         `未开通交易权限，请联系业务人员`,
		BUSINESS_PLANCODE_CANNNOT_BE_EMPTY_ERR_CODE:   `业务方案未设置，请联系业务人员`,
		BUSINEDD_PLAN_NOT_FOUND_ERR_CODE:              `查找不到业务方案%v或该业务方案未关联到%v，请联系业务人员`,
		SYMBOL_CANNNOT_BE_EMPTY_ERR_CODE:              `标的代码不能为空`,
		SYMBOL_NOT_FOUND_ERR_CODE:                     `查找不到标的:%v`,
		OPEN_CLOSE_CANNNOT_BE_EMPTY_ERR_CODE:          `开平仓标识未设置`,
		SYMBOL_NOT_IN_WHITE_POOL_ERR_CODE:             `标的代码(%v)不在标的白名单，请联系业务人员`,
		NUM_VALUE_CANNNOT_BE_EMPTY_ERR_CODE:           `%s要求不能为空且为正数`,
		CAP_ACCT_NOT_FOUND_ERR_CODE:                   `资金账户需满足业务范围为【收益互换或混用】且币种为【CNY】`,
		QTY_NOT_ENOUGH_ERR_CODE:                       `%s不足`,
		PAR_VALUE_NOT_FOUD_ERR_CODE:                   `找不到标的%s的面值，当前标的不支持下单，请联系业务人员`,
		SECURITY_ID_NOT_FOUD_ERR_CODE:                 `找不到标的%s的ID，当前标的不支持下单，请联系业务人员`,
		CANNOT_FREEZE_CAPITAL_ON_TRADE_START_ERR_CODE: `无法在开始执行订单%s时冻结资金`,
		CAPITAL_AMOUNT_NOT_ENOUGH_ERR_CODE:            `可用余额不足`,
		CAPITAL_AMOUNT_NEED_REVIEW_ERR_CODE:           `可用余额不足，订单已转为待审批，请联系业务人员`,
		CLORDID_CANNOT_BE_EMPTY_ERR_CODE:              `订单号不能为空`,
		SETTLE_SPEED_NOT_CORRECT_ERR_CODE:             `清算速度应设置为 T+0 或 T+1`,
		ILLEGAL_FIT_TAG_ERR_CODE:                      `FIX标签 %v<%v> 不能为空且须按正确的值类型赋值，详情请查阅API文档`,
		RATE_LIMIT_EXCEEDED_ERR_CODE:                  `报、撤单频率太高（大于%v笔/秒），请稍后重试`,
		PRODUCT_ACCT_NOT_FOUND_ERR_CODE:               `找不到产品账户(%v)或您(%v)无该产品的操作权限，请联系业务人员`,
		QUOTA_LIMIT_EXCEEDED_ERR_CODE:                 `限额检查未通过：%v`,
		ONLY_SUPPORT_BUY_ORDER_ERR_CODE:               `当前只支持多头交易`,
		ONLY_SUPPORT_PRICE_LIMIT_ORDER_ERR_CODE:       `当前只能支持限价单`,
		QUOTA_LIMIT_EXCEEDED_NEED_REVIEW_ERR_CODE:     `限额检查未通过：%v，订单已转为待审批，请联系业务人员`,
		APP_ORD_ID_TOO_LONG_ERR_CODE:                  `客户订单号太长，长度限制:%d`,
		GENERIC_VALUE_NOT_CORRECT_ERR_CODE:            `%s`,
		COMMISSION_NOT_FOUND_ERR_CODE:                 `无法找到订单的佣金参数，请联系业务人员`,
		INTEREST_NOT_FOUND_ERR_CODE:                   `无法找到订单的利息参数，请联系业务人员`,
		NOT_IN_T0_TRADING_TIME_ERR_CODE:               `%s后不可进行T+0卖出交易`,
		SHORT_SELL_AUTH_NOT_CONFIG_ERR_CODE:           `空头开仓的业务权限未配置，请联系业务人员`,
		SHORT_SELL_SIMBOL_ERR_CODE:                    `%s不可用于空头开仓，请联系业务人员`,
		CUST_QUAL_NOT_CORRECT_ERR_CODE:                `您的资质不满足业务要求，请联系业务人员`,
	})
}
